name: frontend-stanging

on:
  workflow_run:
    workflows:
      - Fastie.Saigon Frontend CI/CD
    types:
      - completed

jobs:
  deploy-preview:
    name: Frontend Stanging
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      - name: Deploy to staging
        run: |
          echo "[deploy] Ready to deploy to staging environment"
          echo "[deploy] Client app build available"
          echo "[deploy] Admin app build available"
          echo "[deploy] Restaurant app build available"
          # Add your deployment commands here
          # Example: Deploy to Netlify, Vercel, AWS S3, etc.
